version: "3.9"
services:
    nginx:
        container_name: nginx-file-server
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8081:80
        volumes:
            - .:/home/files